// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logic_server.proto

#ifndef PROTOBUF_logic_5fserver_2eproto__INCLUDED
#define PROTOBUF_logic_5fserver_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace logic_server {

	// Internal implementation detail -- do not call these.
	void protobuf_AddDesc_logic_5fserver_2eproto();
	void protobuf_InitDefaults_logic_5fserver_2eproto();
	void protobuf_AssignDesc_logic_5fserver_2eproto();
	void protobuf_ShutdownFile_logic_5fserver_2eproto();

	class packet_enter_ans;
	class packet_enter_req;
	class packet_game_state_ntf;
	class packet_process_turn_ans;
	class packet_process_turn_req;

	enum message_type {
		ENTER_REQ = 0,
		ENTER_ANS = 1,
		GAME_STATE_NTF = 2,
		PROCESS_TURN_REQ = 3,
		PROCESS_TURN_ANS = 4
	};
	bool message_type_IsValid(int value);
	const message_type message_type_MIN = ENTER_REQ;
	const message_type message_type_MAX = PROCESS_TURN_ANS;
	const int message_type_ARRAYSIZE = message_type_MAX + 1;

	const ::google::protobuf::EnumDescriptor* message_type_descriptor();
	inline const ::std::string& message_type_Name(message_type value) {
		return ::google::protobuf::internal::NameOfEnum(
			message_type_descriptor(), value);
	}
	inline bool message_type_Parse(
		const ::std::string& name, message_type* value) {
		return ::google::protobuf::internal::ParseNamedEnum<message_type>(
			message_type_descriptor(), name, value);
	}
	// ===================================================================

	class packet_enter_req : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_enter_req) */ {
	public:
		packet_enter_req();
		virtual ~packet_enter_req();

		packet_enter_req(const packet_enter_req& from);

		inline packet_enter_req& operator=(const packet_enter_req& from) {
			CopyFrom(from);
			return *this;
		}

		inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
			return _internal_metadata_.unknown_fields();
		}

		inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
			return _internal_metadata_.mutable_unknown_fields();
		}

		static const ::google::protobuf::Descriptor* descriptor();
		static const packet_enter_req& default_instance();

		static const packet_enter_req* internal_default_instance();

		void Swap(packet_enter_req* other);

		// implements Message ----------------------------------------------

		inline packet_enter_req* New() const { return New(NULL); }

		packet_enter_req* New(::google::protobuf::Arena* arena) const;
		void CopyFrom(const ::google::protobuf::Message& from);
		void MergeFrom(const ::google::protobuf::Message& from);
		void CopyFrom(const packet_enter_req& from);
		void MergeFrom(const packet_enter_req& from);
		void Clear();
		bool IsInitialized() const;

		size_t ByteSizeLong() const;
		bool MergePartialFromCodedStream(
			::google::protobuf::io::CodedInputStream* input);
		void SerializeWithCachedSizes(
			::google::protobuf::io::CodedOutputStream* output) const;
		::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
			bool deterministic, ::google::protobuf::uint8* output) const;
		::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
			return InternalSerializeWithCachedSizesToArray(false, output);
		}
		int GetCachedSize() const { return _cached_size_; }
	private:
		void SharedCtor();
		void SharedDtor();
		void SetCachedSize(int size) const;
		void InternalSwap(packet_enter_req* other);
		void UnsafeMergeFrom(const packet_enter_req& from);
	private:
		inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
			return _internal_metadata_.arena();
		}
		inline void* MaybeArenaPtr() const {
			return _internal_metadata_.raw_arena_ptr();
		}
	public:

		::google::protobuf::Metadata GetMetadata() const;

		// nested types ----------------------------------------------------

		// accessors -------------------------------------------------------

		// required int32 player_key = 1;
		bool has_player_key() const;
		void clear_player_key();
		static const int kPlayerKeyFieldNumber = 1;
		::google::protobuf::int32 player_key() const;
		void set_player_key(::google::protobuf::int32 value);

		// required int32 room_key = 2;
		bool has_room_key() const;
		void clear_room_key();
		static const int kRoomKeyFieldNumber = 2;
		::google::protobuf::int32 room_key() const;
		void set_room_key(::google::protobuf::int32 value);

		// @@protoc_insertion_point(class_scope:logic_server.packet_enter_req)
	private:
		inline void set_has_player_key();
		inline void clear_has_player_key();
		inline void set_has_room_key();
		inline void clear_has_room_key();

		// helper for ByteSizeLong()
		size_t RequiredFieldsByteSizeFallback() const;

		::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
		::google::protobuf::internal::HasBits<1> _has_bits_;
		mutable int _cached_size_;
		::google::protobuf::int32 player_key_;
		::google::protobuf::int32 room_key_;
		friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
		friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
		friend void protobuf_AssignDesc_logic_5fserver_2eproto();
		friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

		void InitAsDefaultInstance();
	};
	extern ::google::protobuf::internal::ExplicitlyConstructed<packet_enter_req> packet_enter_req_default_instance_;

	// -------------------------------------------------------------------

	class packet_enter_ans : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_enter_ans) */ {
	public:
		packet_enter_ans();
		virtual ~packet_enter_ans();

		packet_enter_ans(const packet_enter_ans& from);

		inline packet_enter_ans& operator=(const packet_enter_ans& from) {
			CopyFrom(from);
			return *this;
		}

		inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
			return _internal_metadata_.unknown_fields();
		}

		inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
			return _internal_metadata_.mutable_unknown_fields();
		}

		static const ::google::protobuf::Descriptor* descriptor();
		static const packet_enter_ans& default_instance();

		static const packet_enter_ans* internal_default_instance();

		void Swap(packet_enter_ans* other);

		// implements Message ----------------------------------------------

		inline packet_enter_ans* New() const { return New(NULL); }

		packet_enter_ans* New(::google::protobuf::Arena* arena) const;
		void CopyFrom(const ::google::protobuf::Message& from);
		void MergeFrom(const ::google::protobuf::Message& from);
		void CopyFrom(const packet_enter_ans& from);
		void MergeFrom(const packet_enter_ans& from);
		void Clear();
		bool IsInitialized() const;

		size_t ByteSizeLong() const;
		bool MergePartialFromCodedStream(
			::google::protobuf::io::CodedInputStream* input);
		void SerializeWithCachedSizes(
			::google::protobuf::io::CodedOutputStream* output) const;
		::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
			bool deterministic, ::google::protobuf::uint8* output) const;
		::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
			return InternalSerializeWithCachedSizesToArray(false, output);
		}
		int GetCachedSize() const { return _cached_size_; }
	private:
		void SharedCtor();
		void SharedDtor();
		void SetCachedSize(int size) const;
		void InternalSwap(packet_enter_ans* other);
		void UnsafeMergeFrom(const packet_enter_ans& from);
	private:
		inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
			return _internal_metadata_.arena();
		}
		inline void* MaybeArenaPtr() const {
			return _internal_metadata_.raw_arena_ptr();
		}
	public:

		::google::protobuf::Metadata GetMetadata() const;

		// nested types ----------------------------------------------------

		// accessors -------------------------------------------------------

		// required int32 result = 1;
		bool has_result() const;
		void clear_result();
		static const int kResultFieldNumber = 1;
		::google::protobuf::int32 result() const;
		void set_result(::google::protobuf::int32 value);

		// @@protoc_insertion_point(class_scope:logic_server.packet_enter_ans)
	private:
		inline void set_has_result();
		inline void clear_has_result();

		::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
		::google::protobuf::internal::HasBits<1> _has_bits_;
		mutable int _cached_size_;
		::google::protobuf::int32 result_;
		friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
		friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
		friend void protobuf_AssignDesc_logic_5fserver_2eproto();
		friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

		void InitAsDefaultInstance();
	};
	extern ::google::protobuf::internal::ExplicitlyConstructed<packet_enter_ans> packet_enter_ans_default_instance_;

	// -------------------------------------------------------------------

	class packet_game_state_ntf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_game_state_ntf) */ {
	public:
		packet_game_state_ntf();
		virtual ~packet_game_state_ntf();

		packet_game_state_ntf(const packet_game_state_ntf& from);

		inline packet_game_state_ntf& operator=(const packet_game_state_ntf& from) {
			CopyFrom(from);
			return *this;
		}

		inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
			return _internal_metadata_.unknown_fields();
		}

		inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
			return _internal_metadata_.mutable_unknown_fields();
		}

		static const ::google::protobuf::Descriptor* descriptor();
		static const packet_game_state_ntf& default_instance();

		static const packet_game_state_ntf* internal_default_instance();

		void Swap(packet_game_state_ntf* other);

		// implements Message ----------------------------------------------

		inline packet_game_state_ntf* New() const { return New(NULL); }

		packet_game_state_ntf* New(::google::protobuf::Arena* arena) const;
		void CopyFrom(const ::google::protobuf::Message& from);
		void MergeFrom(const ::google::protobuf::Message& from);
		void CopyFrom(const packet_game_state_ntf& from);
		void MergeFrom(const packet_game_state_ntf& from);
		void Clear();
		bool IsInitialized() const;

		size_t ByteSizeLong() const;
		bool MergePartialFromCodedStream(
			::google::protobuf::io::CodedInputStream* input);
		void SerializeWithCachedSizes(
			::google::protobuf::io::CodedOutputStream* output) const;
		::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
			bool deterministic, ::google::protobuf::uint8* output) const;
		::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
			return InternalSerializeWithCachedSizesToArray(false, output);
		}
		int GetCachedSize() const { return _cached_size_; }
	private:
		void SharedCtor();
		void SharedDtor();
		void SetCachedSize(int size) const;
		void InternalSwap(packet_game_state_ntf* other);
		void UnsafeMergeFrom(const packet_game_state_ntf& from);
	private:
		inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
			return _internal_metadata_.arena();
		}
		inline void* MaybeArenaPtr() const {
			return _internal_metadata_.raw_arena_ptr();
		}
	public:

		::google::protobuf::Metadata GetMetadata() const;

		// nested types ----------------------------------------------------

		// accessors -------------------------------------------------------

		// required int32 state = 1;
		bool has_state() const;
		void clear_state();
		static const int kStateFieldNumber = 1;
		::google::protobuf::int32 state() const;
		void set_state(::google::protobuf::int32 value);

		// @@protoc_insertion_point(class_scope:logic_server.packet_game_state_ntf)
	private:
		inline void set_has_state();
		inline void clear_has_state();

		::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
		::google::protobuf::internal::HasBits<1> _has_bits_;
		mutable int _cached_size_;
		::google::protobuf::int32 state_;
		friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
		friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
		friend void protobuf_AssignDesc_logic_5fserver_2eproto();
		friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

		void InitAsDefaultInstance();
	};
	extern ::google::protobuf::internal::ExplicitlyConstructed<packet_game_state_ntf> packet_game_state_ntf_default_instance_;

	// -------------------------------------------------------------------

	class packet_process_turn_req : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_process_turn_req) */ {
	public:
		packet_process_turn_req();
		virtual ~packet_process_turn_req();

		packet_process_turn_req(const packet_process_turn_req& from);

		inline packet_process_turn_req& operator=(const packet_process_turn_req& from) {
			CopyFrom(from);
			return *this;
		}

		inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
			return _internal_metadata_.unknown_fields();
		}

		inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
			return _internal_metadata_.mutable_unknown_fields();
		}

		static const ::google::protobuf::Descriptor* descriptor();
		static const packet_process_turn_req& default_instance();

		static const packet_process_turn_req* internal_default_instance();

		void Swap(packet_process_turn_req* other);

		// implements Message ----------------------------------------------

		inline packet_process_turn_req* New() const { return New(NULL); }

		packet_process_turn_req* New(::google::protobuf::Arena* arena) const;
		void CopyFrom(const ::google::protobuf::Message& from);
		void MergeFrom(const ::google::protobuf::Message& from);
		void CopyFrom(const packet_process_turn_req& from);
		void MergeFrom(const packet_process_turn_req& from);
		void Clear();
		bool IsInitialized() const;

		size_t ByteSizeLong() const;
		bool MergePartialFromCodedStream(
			::google::protobuf::io::CodedInputStream* input);
		void SerializeWithCachedSizes(
			::google::protobuf::io::CodedOutputStream* output) const;
		::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
			bool deterministic, ::google::protobuf::uint8* output) const;
		::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
			return InternalSerializeWithCachedSizesToArray(false, output);
		}
		int GetCachedSize() const { return _cached_size_; }
	private:
		void SharedCtor();
		void SharedDtor();
		void SetCachedSize(int size) const;
		void InternalSwap(packet_process_turn_req* other);
		void UnsafeMergeFrom(const packet_process_turn_req& from);
	private:
		inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
			return _internal_metadata_.arena();
		}
		inline void* MaybeArenaPtr() const {
			return _internal_metadata_.raw_arena_ptr();
		}
	public:

		::google::protobuf::Metadata GetMetadata() const;

		// nested types ----------------------------------------------------

		// accessors -------------------------------------------------------

		// required int32 money = 1;
		bool has_money() const;
		void clear_money();
		static const int kMoneyFieldNumber = 1;
		::google::protobuf::int32 money() const;
		void set_money(::google::protobuf::int32 value);

		// required int32 total_money = 2;
		bool has_total_money() const;
		void clear_total_money();
		static const int kTotalMoneyFieldNumber = 2;
		::google::protobuf::int32 total_money() const;
		void set_total_money(::google::protobuf::int32 value);

		// required int32 card_number = 3;
		bool has_card_number() const;
		void clear_card_number();
		static const int kCardNumberFieldNumber = 3;
		::google::protobuf::int32 card_number() const;
		void set_card_number(::google::protobuf::int32 value);

		// required int32 public_card_number_1 = 4;
		bool has_public_card_number_1() const;
		void clear_public_card_number_1();
		static const int kPublicCardNumber1FieldNumber = 4;
		::google::protobuf::int32 public_card_number_1() const;
		void set_public_card_number_1(::google::protobuf::int32 value);

		// required int32 public_card_number_2 = 5;
		bool has_public_card_number_2() const;
		void clear_public_card_number_2();
		static const int kPublicCardNumber2FieldNumber = 5;
		::google::protobuf::int32 public_card_number_2() const;
		void set_public_card_number_2(::google::protobuf::int32 value);

		// @@protoc_insertion_point(class_scope:logic_server.packet_process_turn_req)
	private:
		inline void set_has_money();
		inline void clear_has_money();
		inline void set_has_total_money();
		inline void clear_has_total_money();
		inline void set_has_card_number();
		inline void clear_has_card_number();
		inline void set_has_public_card_number_1();
		inline void clear_has_public_card_number_1();
		inline void set_has_public_card_number_2();
		inline void clear_has_public_card_number_2();

		// helper for ByteSizeLong()
		size_t RequiredFieldsByteSizeFallback() const;

		::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
		::google::protobuf::internal::HasBits<1> _has_bits_;
		mutable int _cached_size_;
		::google::protobuf::int32 money_;
		::google::protobuf::int32 total_money_;
		::google::protobuf::int32 card_number_;
		::google::protobuf::int32 public_card_number_1_;
		::google::protobuf::int32 public_card_number_2_;
		friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
		friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
		friend void protobuf_AssignDesc_logic_5fserver_2eproto();
		friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

		void InitAsDefaultInstance();
	};
	extern ::google::protobuf::internal::ExplicitlyConstructed<packet_process_turn_req> packet_process_turn_req_default_instance_;

	// -------------------------------------------------------------------

	class packet_process_turn_ans : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:logic_server.packet_process_turn_ans) */ {
	public:
		packet_process_turn_ans();
		virtual ~packet_process_turn_ans();

		packet_process_turn_ans(const packet_process_turn_ans& from);

		inline packet_process_turn_ans& operator=(const packet_process_turn_ans& from) {
			CopyFrom(from);
			return *this;
		}

		inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
			return _internal_metadata_.unknown_fields();
		}

		inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
			return _internal_metadata_.mutable_unknown_fields();
		}

		static const ::google::protobuf::Descriptor* descriptor();
		static const packet_process_turn_ans& default_instance();

		static const packet_process_turn_ans* internal_default_instance();

		void Swap(packet_process_turn_ans* other);

		// implements Message ----------------------------------------------

		inline packet_process_turn_ans* New() const { return New(NULL); }

		packet_process_turn_ans* New(::google::protobuf::Arena* arena) const;
		void CopyFrom(const ::google::protobuf::Message& from);
		void MergeFrom(const ::google::protobuf::Message& from);
		void CopyFrom(const packet_process_turn_ans& from);
		void MergeFrom(const packet_process_turn_ans& from);
		void Clear();
		bool IsInitialized() const;

		size_t ByteSizeLong() const;
		bool MergePartialFromCodedStream(
			::google::protobuf::io::CodedInputStream* input);
		void SerializeWithCachedSizes(
			::google::protobuf::io::CodedOutputStream* output) const;
		::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
			bool deterministic, ::google::protobuf::uint8* output) const;
		::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
			return InternalSerializeWithCachedSizesToArray(false, output);
		}
		int GetCachedSize() const { return _cached_size_; }
	private:
		void SharedCtor();
		void SharedDtor();
		void SetCachedSize(int size) const;
		void InternalSwap(packet_process_turn_ans* other);
		void UnsafeMergeFrom(const packet_process_turn_ans& from);
	private:
		inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
			return _internal_metadata_.arena();
		}
		inline void* MaybeArenaPtr() const {
			return _internal_metadata_.raw_arena_ptr();
		}
	public:

		::google::protobuf::Metadata GetMetadata() const;

		// nested types ----------------------------------------------------

		// accessors -------------------------------------------------------

		// required int32 player_key = 1;
		bool has_player_key() const;
		void clear_player_key();
		static const int kPlayerKeyFieldNumber = 1;
		::google::protobuf::int32 player_key() const;
		void set_player_key(::google::protobuf::int32 value);

		// required int32 money = 2;
		bool has_money() const;
		void clear_money();
		static const int kMoneyFieldNumber = 2;
		::google::protobuf::int32 money() const;
		void set_money(::google::protobuf::int32 value);

		// @@protoc_insertion_point(class_scope:logic_server.packet_process_turn_ans)
	private:
		inline void set_has_player_key();
		inline void clear_has_player_key();
		inline void set_has_money();
		inline void clear_has_money();

		// helper for ByteSizeLong()
		size_t RequiredFieldsByteSizeFallback() const;

		::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
		::google::protobuf::internal::HasBits<1> _has_bits_;
		mutable int _cached_size_;
		::google::protobuf::int32 player_key_;
		::google::protobuf::int32 money_;
		friend void  protobuf_InitDefaults_logic_5fserver_2eproto_impl();
		friend void  protobuf_AddDesc_logic_5fserver_2eproto_impl();
		friend void protobuf_AssignDesc_logic_5fserver_2eproto();
		friend void protobuf_ShutdownFile_logic_5fserver_2eproto();

		void InitAsDefaultInstance();
	};
	extern ::google::protobuf::internal::ExplicitlyConstructed<packet_process_turn_ans> packet_process_turn_ans_default_instance_;

	// ===================================================================


	// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
	// packet_enter_req

	// required int32 player_key = 1;
	inline bool packet_enter_req::has_player_key() const {
		return (_has_bits_[0] & 0x00000001u) != 0;
	}
	inline void packet_enter_req::set_has_player_key() {
		_has_bits_[0] |= 0x00000001u;
	}
	inline void packet_enter_req::clear_has_player_key() {
		_has_bits_[0] &= ~0x00000001u;
	}
	inline void packet_enter_req::clear_player_key() {
		player_key_ = 0;
		clear_has_player_key();
	}
	inline ::google::protobuf::int32 packet_enter_req::player_key() const {
		// @@protoc_insertion_point(field_get:logic_server.packet_enter_req.player_key)
		return player_key_;
	}
	inline void packet_enter_req::set_player_key(::google::protobuf::int32 value) {
		set_has_player_key();
		player_key_ = value;
		// @@protoc_insertion_point(field_set:logic_server.packet_enter_req.player_key)
	}

	// required int32 room_key = 2;
	inline bool packet_enter_req::has_room_key() const {
		return (_has_bits_[0] & 0x00000002u) != 0;
	}
	inline void packet_enter_req::set_has_room_key() {
		_has_bits_[0] |= 0x00000002u;
	}
	inline void packet_enter_req::clear_has_room_key() {
		_has_bits_[0] &= ~0x00000002u;
	}
	inline void packet_enter_req::clear_room_key() {
		room_key_ = 0;
		clear_has_room_key();
	}
	inline ::google::protobuf::int32 packet_enter_req::room_key() const {
		// @@protoc_insertion_point(field_get:logic_server.packet_enter_req.room_key)
		return room_key_;
	}
	inline void packet_enter_req::set_room_key(::google::protobuf::int32 value) {
		set_has_room_key();
		room_key_ = value;
		// @@protoc_insertion_point(field_set:logic_server.packet_enter_req.room_key)
	}

	inline const packet_enter_req* packet_enter_req::internal_default_instance() {
		return &packet_enter_req_default_instance_.get();
	}
	// -------------------------------------------------------------------

	// packet_enter_ans

	// required int32 result = 1;
	inline bool packet_enter_ans::has_result() const {
		return (_has_bits_[0] & 0x00000001u) != 0;
	}
	inline void packet_enter_ans::set_has_result() {
		_has_bits_[0] |= 0x00000001u;
	}
	inline void packet_enter_ans::clear_has_result() {
		_has_bits_[0] &= ~0x00000001u;
	}
	inline void packet_enter_ans::clear_result() {
		result_ = 0;
		clear_has_result();
	}
	inline ::google::protobuf::int32 packet_enter_ans::result() const {
		// @@protoc_insertion_point(field_get:logic_server.packet_enter_ans.result)
		return result_;
	}
	inline void packet_enter_ans::set_result(::google::protobuf::int32 value) {
		set_has_result();
		result_ = value;
		// @@protoc_insertion_point(field_set:logic_server.packet_enter_ans.result)
	}

	inline const packet_enter_ans* packet_enter_ans::internal_default_instance() {
		return &packet_enter_ans_default_instance_.get();
	}
	// -------------------------------------------------------------------

	// packet_game_state_ntf

	// required int32 state = 1;
	inline bool packet_game_state_ntf::has_state() const {
		return (_has_bits_[0] & 0x00000001u) != 0;
	}
	inline void packet_game_state_ntf::set_has_state() {
		_has_bits_[0] |= 0x00000001u;
	}
	inline void packet_game_state_ntf::clear_has_state() {
		_has_bits_[0] &= ~0x00000001u;
	}
	inline void packet_game_state_ntf::clear_state() {
		state_ = 0;
		clear_has_state();
	}
	inline ::google::protobuf::int32 packet_game_state_ntf::state() const {
		// @@protoc_insertion_point(field_get:logic_server.packet_game_state_ntf.state)
		return state_;
	}
	inline void packet_game_state_ntf::set_state(::google::protobuf::int32 value) {
		set_has_state();
		state_ = value;
		// @@protoc_insertion_point(field_set:logic_server.packet_game_state_ntf.state)
	}

	inline const packet_game_state_ntf* packet_game_state_ntf::internal_default_instance() {
		return &packet_game_state_ntf_default_instance_.get();
	}
	// -------------------------------------------------------------------

	// packet_process_turn_req

	// required int32 money = 1;
	inline bool packet_process_turn_req::has_money() const {
		return (_has_bits_[0] & 0x00000001u) != 0;
	}
	inline void packet_process_turn_req::set_has_money() {
		_has_bits_[0] |= 0x00000001u;
	}
	inline void packet_process_turn_req::clear_has_money() {
		_has_bits_[0] &= ~0x00000001u;
	}
	inline void packet_process_turn_req::clear_money() {
		money_ = 0;
		clear_has_money();
	}
	inline ::google::protobuf::int32 packet_process_turn_req::money() const {
		// @@protoc_insertion_point(field_get:logic_server.packet_process_turn_req.money)
		return money_;
	}
	inline void packet_process_turn_req::set_money(::google::protobuf::int32 value) {
		set_has_money();
		money_ = value;
		// @@protoc_insertion_point(field_set:logic_server.packet_process_turn_req.money)
	}

	// required int32 total_money = 2;
	inline bool packet_process_turn_req::has_total_money() const {
		return (_has_bits_[0] & 0x00000002u) != 0;
	}
	inline void packet_process_turn_req::set_has_total_money() {
		_has_bits_[0] |= 0x00000002u;
	}
	inline void packet_process_turn_req::clear_has_total_money() {
		_has_bits_[0] &= ~0x00000002u;
	}
	inline void packet_process_turn_req::clear_total_money() {
		total_money_ = 0;
		clear_has_total_money();
	}
	inline ::google::protobuf::int32 packet_process_turn_req::total_money() const {
		// @@protoc_insertion_point(field_get:logic_server.packet_process_turn_req.total_money)
		return total_money_;
	}
	inline void packet_process_turn_req::set_total_money(::google::protobuf::int32 value) {
		set_has_total_money();
		total_money_ = value;
		// @@protoc_insertion_point(field_set:logic_server.packet_process_turn_req.total_money)
	}

	// required int32 card_number = 3;
	inline bool packet_process_turn_req::has_card_number() const {
		return (_has_bits_[0] & 0x00000004u) != 0;
	}
	inline void packet_process_turn_req::set_has_card_number() {
		_has_bits_[0] |= 0x00000004u;
	}
	inline void packet_process_turn_req::clear_has_card_number() {
		_has_bits_[0] &= ~0x00000004u;
	}
	inline void packet_process_turn_req::clear_card_number() {
		card_number_ = 0;
		clear_has_card_number();
	}
	inline ::google::protobuf::int32 packet_process_turn_req::card_number() const {
		// @@protoc_insertion_point(field_get:logic_server.packet_process_turn_req.card_number)
		return card_number_;
	}
	inline void packet_process_turn_req::set_card_number(::google::protobuf::int32 value) {
		set_has_card_number();
		card_number_ = value;
		// @@protoc_insertion_point(field_set:logic_server.packet_process_turn_req.card_number)
	}

	// required int32 public_card_number_1 = 4;
	inline bool packet_process_turn_req::has_public_card_number_1() const {
		return (_has_bits_[0] & 0x00000008u) != 0;
	}
	inline void packet_process_turn_req::set_has_public_card_number_1() {
		_has_bits_[0] |= 0x00000008u;
	}
	inline void packet_process_turn_req::clear_has_public_card_number_1() {
		_has_bits_[0] &= ~0x00000008u;
	}
	inline void packet_process_turn_req::clear_public_card_number_1() {
		public_card_number_1_ = 0;
		clear_has_public_card_number_1();
	}
	inline ::google::protobuf::int32 packet_process_turn_req::public_card_number_1() const {
		// @@protoc_insertion_point(field_get:logic_server.packet_process_turn_req.public_card_number_1)
		return public_card_number_1_;
	}
	inline void packet_process_turn_req::set_public_card_number_1(::google::protobuf::int32 value) {
		set_has_public_card_number_1();
		public_card_number_1_ = value;
		// @@protoc_insertion_point(field_set:logic_server.packet_process_turn_req.public_card_number_1)
	}

	// required int32 public_card_number_2 = 5;
	inline bool packet_process_turn_req::has_public_card_number_2() const {
		return (_has_bits_[0] & 0x00000010u) != 0;
	}
	inline void packet_process_turn_req::set_has_public_card_number_2() {
		_has_bits_[0] |= 0x00000010u;
	}
	inline void packet_process_turn_req::clear_has_public_card_number_2() {
		_has_bits_[0] &= ~0x00000010u;
	}
	inline void packet_process_turn_req::clear_public_card_number_2() {
		public_card_number_2_ = 0;
		clear_has_public_card_number_2();
	}
	inline ::google::protobuf::int32 packet_process_turn_req::public_card_number_2() const {
		// @@protoc_insertion_point(field_get:logic_server.packet_process_turn_req.public_card_number_2)
		return public_card_number_2_;
	}
	inline void packet_process_turn_req::set_public_card_number_2(::google::protobuf::int32 value) {
		set_has_public_card_number_2();
		public_card_number_2_ = value;
		// @@protoc_insertion_point(field_set:logic_server.packet_process_turn_req.public_card_number_2)
	}

	inline const packet_process_turn_req* packet_process_turn_req::internal_default_instance() {
		return &packet_process_turn_req_default_instance_.get();
	}
	// -------------------------------------------------------------------

	// packet_process_turn_ans

	// required int32 player_key = 1;
	inline bool packet_process_turn_ans::has_player_key() const {
		return (_has_bits_[0] & 0x00000001u) != 0;
	}
	inline void packet_process_turn_ans::set_has_player_key() {
		_has_bits_[0] |= 0x00000001u;
	}
	inline void packet_process_turn_ans::clear_has_player_key() {
		_has_bits_[0] &= ~0x00000001u;
	}
	inline void packet_process_turn_ans::clear_player_key() {
		player_key_ = 0;
		clear_has_player_key();
	}
	inline ::google::protobuf::int32 packet_process_turn_ans::player_key() const {
		// @@protoc_insertion_point(field_get:logic_server.packet_process_turn_ans.player_key)
		return player_key_;
	}
	inline void packet_process_turn_ans::set_player_key(::google::protobuf::int32 value) {
		set_has_player_key();
		player_key_ = value;
		// @@protoc_insertion_point(field_set:logic_server.packet_process_turn_ans.player_key)
	}

	// required int32 money = 2;
	inline bool packet_process_turn_ans::has_money() const {
		return (_has_bits_[0] & 0x00000002u) != 0;
	}
	inline void packet_process_turn_ans::set_has_money() {
		_has_bits_[0] |= 0x00000002u;
	}
	inline void packet_process_turn_ans::clear_has_money() {
		_has_bits_[0] &= ~0x00000002u;
	}
	inline void packet_process_turn_ans::clear_money() {
		money_ = 0;
		clear_has_money();
	}
	inline ::google::protobuf::int32 packet_process_turn_ans::money() const {
		// @@protoc_insertion_point(field_get:logic_server.packet_process_turn_ans.money)
		return money_;
	}
	inline void packet_process_turn_ans::set_money(::google::protobuf::int32 value) {
		set_has_money();
		money_ = value;
		// @@protoc_insertion_point(field_set:logic_server.packet_process_turn_ans.money)
	}

	inline const packet_process_turn_ans* packet_process_turn_ans::internal_default_instance() {
		return &packet_process_turn_ans_default_instance_.get();
	}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
	// -------------------------------------------------------------------

	// -------------------------------------------------------------------

	// -------------------------------------------------------------------

	// -------------------------------------------------------------------


	// @@protoc_insertion_point(namespace_scope)

}  // namespace logic_server

#ifndef SWIG
namespace google {
	namespace protobuf {

		template <> struct is_proto_enum< ::logic_server::message_type> : ::google::protobuf::internal::true_type {};
		template <>
		inline const EnumDescriptor* GetEnumDescriptor< ::logic_server::message_type>() {
			return ::logic_server::message_type_descriptor();
		}

	}  // namespace protobuf
}  // namespace google
#endif  // SWIG

   // @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_logic_5fserver_2eproto__INCLUDED
